### ISSUE TITLE
install/usage howto

### ISSUE THREAD

**Issue by booo** [basho-labs/luwak#19]
I'm currently trying to install and use the luwak erlang interface but somehow I'm having a hard time. Maybe you can add a few lines of information on how to integrate this into an existing (rebar) project?

Thank you in advance.

**Comment by beerriot** [comment]
Hi, @booo.  The luwak erlang interface in this repo is designed to work only as a component of a Riak cluster.  As such, it's really only possible to integrate it into a project that is also integrating `riak_core` and `riak_kv`.  Instructions for doing that should be relatively straightforward, though.

On the chance that what you want to do instead is use something like Luwak from a project running independently of the Riak cluster, I've created a fork that uses the Erlang Protocol Buffers client instead of the cluster-internal Distributed Erlang client. You can find that code at https://github.com/beerriot/luwak/tree/external.  Be sure to read the section of the readme titled "The external Branch", which outlines differences in that branch, and also links to an example application using it.  Please note that that branch is no more supported by Basho than this branch is.

Cheers.
